services:
  - type: web
    name: rental-price-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    branches:
      production:
        autoDeploy: true
      preview:
        autoDeploy: true

  - type: web
    name: rental-price-streamlit
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app.py"
    branches:
      production:
        autoDeploy: true
      preview:
        autoDeploy: true
